language: python
node_js:
  - 3.6.8
branches:
  only:
  - sphinx_blog

notifications:
  email:
    recipients:
      - 1058862172@qq.com
      - zhishengqianjun@163.com
    on_success: always # default: change
    on_failure: always # default: alway
cache:
  directories:
  - build
  yarn: true
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
install:
 - pip install -r blog.requirement
script:
- make html

after_script:
   - cd ./build/html
   - git init
   - git config user.name "zhishengqianjun"
   - git config user.email "zhishengqianjun@163.com"
   - git add .
   - git commit -m "Update sphinx By TravisCI With Build $TRAVIS_BUILD_NUMBER"
   - git push --force --quiet "https://zhishengqianjun:${CO_TOKEN}@${CO_REF}" master:master
   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
 global:
   # Coding Pages
   - CO_REF: git.dev.tencent.com/zhishengqianjun/blog.git
   - GH_REF: github.com/gaviners/sphinx_blog.git

